/**
 * scripts/slack-alert.js
 * - Sends a summary Slack message after the CI job completes.
 * - Uses SLACK_WEBHOOK_URL secret. Retries with exponential backoff.
 * - On repeated failure, logs fallback file to /tmp for audit.
 *
 * Environment variables (provided by workflow):
 * - SLACK_WEBHOOK_URL
 * - JOB_STATUS (success / failure / cancelled)
 * - REPO, BRANCH, RUN_ID, RUN_NUMBER, ACTOR, EVENT_NAME
 */

const fs = require('fs');
const util = require('util');

const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL;
const JOB_STATUS = process.env.JOB_STATUS || 'unknown';
const REPO = process.env.REPO || 'unknown/repo';
const BRANCH = process.env.BRANCH || 'unknown';
const RUN_ID = process.env.RUN_ID || '';
const RUN_NUMBER = process.env.RUN_NUMBER || '';
const ACTOR = process.env.ACTOR || '';
const EVENT_NAME = process.env.EVENT_NAME || '';

const FALLBACK_LOG = '/tmp/ci-slack-fallback.log';

if (!SLACK_WEBHOOK_URL) {
  console.error('Missing SLACK_WEBHOOK_URL. Writing fallback log.');
  writeFallback({ error: 'Missing SLACK_WEBHOOK_URL', env: { REPO, BRANCH, RUN_ID, RUN_NUMBER, ACTOR, EVENT_NAME, JOB_STATUS } });
  process.exitCode = 1;
  process.exit(1);
}

const statusEmoji = JOB_STATUS === 'success' ? ':white_check_mark:' : JOB_STATUS === 'failure' ? ':x:' : ':warning:';

const message = {
  text: `${statusEmoji} CI ${JOB_STATUS.toUpperCase()} - ${REPO}`,
  blocks: [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*CI ${JOB_STATUS.toUpperCase()}* for *${REPO}*\n*Branch:* ${BRANCH}\n*Run:* <https://github.com/${REPO}/actions/runs/${RUN_ID}|#${RUN_NUMBER}>\n*Triggered by:* ${ACTOR}\n*Event:* ${EVENT_NAME}`
      }
    },
    {
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: `Generated by global.press0 CI`
        }
      ]
    }
  ]
};

(async () => {
  try {
    await postWithRetry(SLACK_WEBHOOK_URL, message, 3);
    console.log('Slack notification sent.');
  } catch (err) {
    console.error('Failed to send Slack notification:', err);
    await writeFallback({ error: err.message, stack: err.stack, payload: message, env: { REPO, BRANCH, RUN_ID, RUN_NUMBER, ACTOR, EVENT_NAME, JOB_STATUS } });
    process.exitCode = 1;
  }
})();

async function postWithRetry(url, payload, retries = 3) {
  let attempt = 0;
  let lastErr;
  while (attempt < retries) {
    try {
      attempt++;
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
        // Node 18 global fetch used; if older node, add node-fetch in package.json
      });
      if (!res.ok) {
        const text = await res.text();
        throw new Error(`Unexpected response ${res.status}: ${text}`);
      }
      return;
    } catch (err) {
      lastErr = err;
      const backoffMs = Math.pow(2, attempt) * 500;
      console.warn(`Slack attempt ${attempt} failed. Retrying in ${backoffMs}ms. Error: ${err.message}`);
      await sleep(backoffMs);
    }
  }
  throw lastErr;
}

async function writeFallback(obj) {
  try {
    const payload = { ts: new Date().toISOString(), obj };
    await fs.promises.appendFile(FALLBACK_LOG, util.format('%O\n', payload), { encoding: 'utf8' });
    console.log(`Wrote fallback log to ${FALLBACK_LOG}`);
  } catch (err) {
    console.error('Failed writing fallback log:', err);
  }
}

function sleep(ms) {
  return new Promise((res) => setTimeout(res, ms));
}
